# Project information
site_name: 'neuroimaging tutorials and resources'
repo_name: 'learn-neuroimaging/tutorials-and-resources'
repo_url: 'https://github.com/learn-neuroimaging/tutorials-and-resources'
# docs_dir: alternative_path # docs/ is the default folder

# This will use Material them
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'light blue'
    accent: 'light blue'

# Pages
nav:
  - Welcome: "index.md"
  - Before you start:
    - About: "01-before-you-start.md"
    - Programming: "programming.md"
  - Planning your study:
      - About: "02-planning-your-study.md"
      - Reproducible research: "reproducible_neuroimaging_research.md"
  - Getting data:
    - About: "03-getting-data.md"
    - Data repositories: "data-repositories.md"
  - Processing:
    - About: "04-processing.md"
    - Computing: "computing.md"
    - MRI: "analysis_software_MRI.md"
    - MEEG: "analysis_software_MEEG.md"
    - Other physiological signals: "analysis_software_physio.md"
    - Learning neuroimaging: "learning_neuroimaging.md"
    - Neuroimaging resources: "neuroimaging_resources.md"
  - Analysis:
    - About: "05-analysis.md"
    - Statistics: "statistics.md"
    - Machine learning and Deep learning: "machine_and_deep_learning.md"
    - The Allen atlas (postmortem gene expression data): "allen_software.md"
  - Quality control:
      - About: "06-quality-control.md"
  - Reporting methods and results:
    - About: "07-reporting-methods-and-results.md"
  - Sharing data, code and results:
    - About: "08-sharing-data-code-and-results.md"
    - Open science: "open_science.md"
  - Appendix: "99-appendix.md"

# list of extension
markdown_extensions:
  - admonition
  - pymdownx.details
